[[language]]
name = "python"
scope = "source.python"
language-servers = ["pyright", "ruff"]

[language.formatter]
command = "ruff"
args = ["format", "-"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
disableOrganizeImports = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "strict"
diagnosticMode = "workspace"

[language-server.ruff]
command = "ruff"
args = ["server", "-q"]
