start-at-login = false

exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

default-root-container-layout = 'tiles'

default-root-container-orientation = 'vertical'

key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 12
inner.vertical =   12
outer.left =       12
outer.bottom =     12
outer.top =        40
outer.right =      12

[mode.main.binding]
# Focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Moving (Rearranging)
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Social(discord, telegram, etc)
alt-s = 'workspace 1'
# Dev (Terminal, etc)
alt-d = 'workspace 2'
# Browser
alt-b = 'workspace 3'
# Testing
alt-t = 'workspace 4'
# Editor
alt-e = 'workspace 5'

alt-shift-s = 'move-node-to-workspace 1'
alt-shift-d = 'move-node-to-workspace 2'
alt-shift-b = 'move-node-to-workspace 3'
alt-shift-t = 'move-node-to-workspace 4'
alt-shift-e = 'move-node-to-workspace 5'

alt-shift-r = 'layout horizontal vertical'

ctrl-alt-right = 'workspace next'
ctrl-alt-left = 'workspace prev'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
r = ['reload-config', 'mode main']

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace 3'

