start-at-login = false

after-startup-command = ['exec-and-forget brew services run sketchybar']
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_event EVENT=WORKSPACE_CHANGE FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]
on-focus-changed = [
  'exec-and-forget sketchybar --trigger aerospace_event EVENT=FOCUS_CHANGED',
  'move-mouse window-lazy-center',
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'

default-root-container-orientation = 'vertical'

key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 12
inner.vertical =   12
outer.left =       12
outer.bottom =     12
outer.top =        48
outer.right =      12

[mode.main.binding]
# Changing layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# Focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Moving (Rearranging)
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Resizing
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Social(discord, telegram, etc)
alt-s = 'workspace social'
# Dev (Terminal, etc)
alt-d = 'workspace dev'
# Browser
alt-w = 'workspace web'
# Terminal
alt-t = 'workspace term'
# Editor
alt-i = 'workspace ide'
# Other
alt-o = 'workspace other'

# Moving apps to workspaces
alt-shift-s = [
  'move-node-to-workspace social',
  'exec-and-forget sketchybar --trigger aerospace_event EVENT=WINDOW_MOVED NEW_WORKSPACE=social',
]
alt-shift-d = [
  'move-node-to-workspace dev',
  'exec-and-forget sketchybar --trigger aerospace_event EVENT=WINDOW_MOVED NEW_WORKSPACE=dev',
]
alt-shift-w = [
  'move-node-to-workspace web',
  'exec-and-forget sketchybar --trigger aerospace_event EVENT=WINDOW_MOVED NEW_WORKSPACE=web',
]
alt-shift-t = [
  'move-node-to-workspace term',
  'exec-and-forget sketchybar --trigger aerospace_event EVENT=WINDOW_MOVED NEW_WORKSPACE=term',
]
alt-shift-i = [
  'move-node-to-workspace ide',
  'exec-and-forget sketchybar --trigger aerospace_event EVENT=WINDOW_MOVED NEW_WORKSPACE=ide',
]
alt-shift-o = [
  'move-node-to-workspace other',
  'exec-and-forget sketchybar --trigger aerospace_event EVENT=WINDOW_MOVED NEW_WORKSPACE=other',
]

ctrl-alt-right = 'workspace next'
ctrl-alt-left = 'workspace prev'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = 'mode main'
r = ['reload-config', 'mode main']
x = ['flatten-workspace-tree', 'mode main']
f = ['layout floating', 'mode main']

alt-h = ['join-with left', 'mode main']
alt-j = ['join-with down', 'mode main']
alt-k = ['join-with up', 'mode main']
alt-l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = ''
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.dexterleng.ProNotes'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace term'

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace web'

