#!/usr/bin/env sh

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

source $CONFIG_DIR/colors.sh

FONT="SF Pro"
PADDINGS=3

sketchybar --bar     height=30                                         \
                     color=$TRANSPARENT                                \
                     shadow=on                                         \
                     position=top                                      \
                     sticky=on                                         \
                     padding_right=7                                   \
                     padding_left=7                                    \
                     corner_radius=9                                   \
                     y_offset=6                                        \
                     margin=12                                         \
                     blur_radius=20                                    \
                     notch_width=0                                     \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Bold:14.0"                       \
                     icon.color=$ICON_COLOR                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$FONT:Semibold:13.0"                  \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     background.padding_right=$PADDINGS                \
                     background.padding_left=$PADDINGS                 \
                     background.height=25                              \
                     background.corner_radius=9                        \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=11                 \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=on

# LEFT SIDE ITEMS
source "$ITEM_DIR/spaces.sh"

# CENTER ITEMS
source "$ITEM_DIR/app_title.sh"

# RIGHT SIDE ITEMS
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/weather.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/keyboard.sh"

sketchybar --add bracket space_list '/space\..*/'                     \
           --set         space_list background.color=$BACKGROUND_1    \
                                    background.padding_left=0

sketchybar --add bracket base_info wifi keyboard battery weather      \
           --set         base_info background.color=$BACKGROUND_1     \
                                   background.padding_right=0

sketchybar --update

echo "sketchybar configuation loaded.."
