import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
dimensions = { lines = 100, columns = 300 }
padding = { x = 4, y = 4 }
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "OnlyLeft"

[scrolling]
history = 50000

[font]
normal = { family = "SFMono Nerd Font", style = "Regular" }
bold = { family = "SFMono Nerd Font", style = "Bold" }
size = 13

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" },
    { key = "Back", mods = "Command", chars = "\u0015" },
    { key = "Right", mods = "Command", chars = "\u0005" },
    { key = "Left", mods = "Command", chars = "\u0001" },
]
